NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-misa-8054-ca-misa.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-misa-8054-ca-misa.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-misa-8054-ca-misa.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-misa-8054-ca-misa.pem
    OrganizationalUnitIdentifier: orderer
