#Requires -RunAsAdministrator
# install.ps1 — vHSM REST API installer for Windows
# Mirrors install.sh for Linux: prompts for credentials, configures HSM + MinIO,
# writes env file under $env:ProgramData\vHSM, and registers a Windows service
# via WinSW (https://github.com/winsw/winsw).

param(
  [switch]$NonInteractive
)

$ErrorActionPreference = "Stop"
$vhsmData = Join-Path $env:ProgramData "vHSM"
$vhsmEnv = Join-Path $vhsmData "vhsmd.env"
$vhsmService = Join-Path $vhsmData "winsw.xml"

function Write-Info($msg) { Write-Host "[INFO]  $msg" -ForegroundColor Blue }
function Write-Ok($msg) { Write-Host "[OK]    $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "[WARN]  $msg" -ForegroundColor Yellow }

if (-not (Test-Path $vhsmData)) { New-Item -ItemType Directory -Path $vhsmData | Out-Null }

# Prompt helpers
function Prompt-Default($question, $default) {
  $ans = Read-Host "$question [$default]"
  if ([string]::IsNullOrWhiteSpace($ans)) { return $default } else { return $ans }
}
function New-RandomSecret($len = 32) {
  $bytes = New-Object byte[] $len
  [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  [Convert]::ToBase64String($bytes)
}

Write-Host "`n══ vHSM Windows Installer ══`n" -ForegroundColor Cyan

$env:VHSM_STORE_BACKEND = Prompt-Default "Store backend (db|ledger)" "db"
$env:VHSM_DB_PATH = Prompt-Default "DB path" (Join-Path $vhsmData "vhsm.sqlite")
$vhsmVaultPath = Prompt-Default "Vault path (leave blank to disable)" ""
if ($vhsmVaultPath) {
  $env:VHSM_VAULT_PATH = $vhsmVaultPath
  $env:VHSM_VAULT_PASSWORD = if ($NonInteractive) { New-RandomSecret } else { Read-Host "Vault password" -AsSecureString | ConvertFrom-SecureString -AsPlainText }
}
# Persist env file
$envContent = @"
# Generated by install.ps1 — $(Get-Date -Format o)
VHSM_STORE_BACKEND=$env:VHSM_STORE_BACKEND
VHSM_DB_PATH=$env:VHSM_DB_PATH
VHSM_VAULT_PATH=$env:VHSM_VAULT_PATH
VHSM_VAULT_PASSWORD=$env:VHSM_VAULT_PASSWORD
"@
Set-Content -Path $vhsmEnv -Value $envContent -Encoding UTF8
Write-Ok "Wrote $vhsmEnv"

# Build Go binary if not present
$exe = Join-Path $PSScriptRoot "vhsmd.exe"
if (-not (Test-Path $exe)) {
  Write-Info "Building Go binary..."
  Push-Location $PSScriptRoot
  go build -o vhsmd.exe ./...
  Pop-Location
}

# WinSW service registration (download WinSW if missing)
$winsw = Join-Path $vhsmData "winsw.exe"
if (-not (Test-Path $winsw)) {
  Write-Info "Downloading WinSW..."
  Invoke-WebRequest -Uri "https://github.com/winsw/winsw/releases/latest/download/WinSW-x64.exe" -OutFile $winsw
}
$xml = @"
<service>
  <id>vhsmd</id>
  <name>vHSM REST API</name>
  <description>Virtual HSM REST API (store=$env:VHSM_STORE_BACKEND)</description>
  <executable>$exe</executable>
  <env name="VHSM_STORE_BACKEND" value="$env:VHSM_STORE_BACKEND"/>
  <env name="VHSM_DB_PATH" value="$env:VHSM_DB_PATH"/>
  <log mode="roll"/>
</service>
"@
Set-Content -Path $vhsmService -Value $xml -Encoding UTF8
& $winsw install $vhsmService
& $winsw start vhsmd
Write-Ok "Service vhsmd installed and started. Logs in $vhsmData\logs"
Write-Host "`nRun 'Get-Service vhsmd' to check status. Env file: $vhsmEnv`n" -ForegroundColor Cyan
