// Package eth provides a minimal go-ethereum based client for anchoring
// Merkle roots onto the MerkleAnchor contract deployed on Sepolia testnet.
//
// This is written against the contract ABI directly (bind.NewBoundContract)
// rather than abigen-generated bindings, since abigen requires running the
// solc + abigen toolchain locally. Functionally equivalent — abigen just
// generates this same kind of code automatically from the ABI/bytecode.
package eth

import (
	"context"
	"crypto/ecdsa"
	"fmt"
	"math/big"
	"strings"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/ethclient"
)

// contractABI must match MerkleAnchor.sol exactly. In a real build, this
// is generated by `solc --abi` and should be loaded from that output
// rather than hand-copied, to avoid drift between the contract and this
// string if the contract is ever updated.
const contractABI = `[
	{"inputs":[{"internalType":"bytes32","name":"merkleRoot","type":"bytes32"},{"internalType":"string","name":"batchId","type":"string"}],"name":"anchorRoot","outputs":[],"stateMutability":"nonpayable","type":"function"},
	{"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"anchorIndex","type":"uint256"},{"indexed":true,"internalType":"bytes32","name":"merkleRoot","type":"bytes32"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"},{"indexed":true,"internalType":"address","name":"submitter","type":"address"},{"indexed":false,"internalType":"string","name":"batchId","type":"string"}],"name":"RootAnchored","type":"event"},
	{"inputs":[],"name":"latestAnchor","outputs":[{"components":[{"internalType":"bytes32","name":"merkleRoot","type":"bytes32"},{"internalType":"uint256","name":"timestamp","type":"uint256"},{"internalType":"address","name":"submitter","type":"address"},{"internalType":"string","name":"batchId","type":"string"}],"internalType":"struct MerkleAnchor.Anchor","name":"","type":"tuple"}],"stateMutability":"view","type":"function"}
]`

// Client wraps a connection to the MerkleAnchor contract on Sepolia.
type Client struct {
	ethClient    *ethclient.Client
	contract     *bind.BoundContract
	contractAddr common.Address
	chainID      *big.Int
	privateKey   *ecdsa.PrivateKey
	fromAddr     common.Address
}

// Config holds connection parameters. RPCEndpoint should be a Sepolia
// RPC URL (e.g. from Infura/Alchemy). PrivateKeyHex is the hex-encoded
// private key (no 0x prefix needed) for the account that will submit
// anchorRoot transactions — this must be the contract owner's key.
type Config struct {
	RPCEndpoint     string
	ContractAddress string
	PrivateKeyHex   string
	ChainID         int64 // Sepolia = 11155111
}

// NewClient connects to the given RPC endpoint and prepares a bound
// contract instance plus signing key for sending transactions.
func NewClient(cfg Config) (*Client, error) {
	ec, err := ethclient.Dial(cfg.RPCEndpoint)
	if err != nil {
		return nil, fmt.Errorf("failed to dial RPC endpoint: %w", err)
	}

	parsedABI, err := abi.JSON(strings.NewReader(contractABI))
	if err != nil {
		return nil, fmt.Errorf("failed to parse contract ABI: %w", err)
	}

	contractAddr := common.HexToAddress(cfg.ContractAddress)
	boundContract := bind.NewBoundContract(contractAddr, parsedABI, ec, ec, ec)

	privKey, err := crypto.HexToECDSA(strings.TrimPrefix(cfg.PrivateKeyHex, "0x"))
	if err != nil {
		return nil, fmt.Errorf("failed to parse private key: %w", err)
	}

	fromAddr := crypto.PubkeyToAddress(privKey.PublicKey)

	return &Client{
		ethClient:    ec,
		contract:     boundContract,
		contractAddr: contractAddr,
		chainID:      big.NewInt(cfg.ChainID),
		privateKey:   privKey,
		fromAddr:     fromAddr,
	}, nil
}

// Close releases the underlying RPC connection.
func (c *Client) Close() {
	c.ethClient.Close()
}

// AnchorRoot submits a transaction calling anchorRoot(merkleRoot, batchId)
// on the contract, signed by the configured private key. Returns the
// transaction object itself so the caller can wait for it to be mined via
// WaitForReceipt.
func (c *Client) AnchorRoot(ctx context.Context, merkleRoot [32]byte, batchID string) (*types.Transaction, error) {
	nonce, err := c.ethClient.PendingNonceAt(ctx, c.fromAddr)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch nonce: %w", err)
	}

	gasPrice, err := c.ethClient.SuggestGasPrice(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to suggest gas price: %w", err)
	}

	auth, err := bind.NewKeyedTransactorWithChainID(c.privateKey, c.chainID)
	if err != nil {
		return nil, fmt.Errorf("failed to create transactor: %w", err)
	}
	auth.Nonce = big.NewInt(int64(nonce))
	auth.GasPrice = gasPrice
	auth.GasLimit = uint64(150000) // generous fixed limit; estimate instead in production
	auth.Context = ctx

	tx, err := c.contract.Transact(auth, "anchorRoot", merkleRoot, batchID)
	if err != nil {
		return nil, fmt.Errorf("anchorRoot transaction failed: %w", err)
	}

	return tx, nil
}

// WaitForReceipt blocks until the given transaction is mined and returns
// its receipt. Caller should check receipt.Status == types.ReceiptStatusSuccessful.
func (c *Client) WaitForReceipt(ctx context.Context, tx *types.Transaction) (*types.Receipt, error) {
	return bind.WaitMined(ctx, c.ethClient, tx)
}

// LatestAnchor reads the latestAnchor() view function and returns the
// most recently anchored root, timestamp, submitter, and batch ID.
type AnchorResult struct {
	MerkleRoot [32]byte
	Timestamp  *big.Int
	Submitter  common.Address
	BatchID    string
}

func (c *Client) LatestAnchor(ctx context.Context) (*AnchorResult, error) {
	var out []interface{}
	err := c.contract.Call(&bind.CallOpts{Context: ctx}, &out, "latestAnchor")
	if err != nil {
		return nil, fmt.Errorf("failed to call latestAnchor: %w", err)
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("unexpected empty result from latestAnchor")
	}

	// The result is the Anchor struct tuple, decoded into an anonymous
	// struct matching the ABI's component order.
	type anchorStruct struct {
		MerkleRoot [32]byte
		Timestamp  *big.Int
		Submitter  common.Address
		BatchId    string
	}
	result, ok := out[0].(anchorStruct)
	if !ok {
		return nil, fmt.Errorf("unexpected type for latestAnchor result")
	}

	return &AnchorResult{
		MerkleRoot: result.MerkleRoot,
		Timestamp:  result.Timestamp,
		Submitter:  result.Submitter,
		BatchID:    result.BatchId,
	}, nil
}
