# Add subdirectories for each component
add_subdirectory(core)
add_subdirectory(threadpool)
add_subdirectory(crypto)
add_subdirectory(persistence)
add_subdirectory(session)
add_subdirectory(keystore)
add_subdirectory(signature_store)
add_subdirectory(pkcs11)
if(VHSM_LEDGER)
    add_subdirectory(ledger)
endif()
# add_subdirectory(admin)
if(VHSM_ADMIN_GRPC)
    add_subdirectory(admin)
endif()
add_subdirectory(notification)